//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insert_BusInfo", Namespace="http://schemas.datacontract.org/2004/07/Bus_Service.Classes")]
    [System.SerializableAttribute()]
    public partial class Insert_BusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusOrgCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusID {
            get {
                return this.BusIDField;
            }
            set {
                if ((this.BusIDField.Equals(value) != true)) {
                    this.BusIDField = value;
                    this.RaisePropertyChanged("BusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusName {
            get {
                return this.BusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNameField, value) != true)) {
                    this.BusNameField = value;
                    this.RaisePropertyChanged("BusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusOrgCapacity {
            get {
                return this.BusOrgCapacityField;
            }
            set {
                if ((this.BusOrgCapacityField.Equals(value) != true)) {
                    this.BusOrgCapacityField = value;
                    this.RaisePropertyChanged("BusOrgCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusType {
            get {
                return this.BusTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BusTypeField, value) != true)) {
                    this.BusTypeField = value;
                    this.RaisePropertyChanged("BusType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insert_RouteInfo", Namespace="http://schemas.datacontract.org/2004/07/Bus_Service.Classes")]
    [System.SerializableAttribute()]
    public partial class Insert_RouteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RouteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteFrom {
            get {
                return this.RouteFromField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteFromField, value) != true)) {
                    this.RouteFromField = value;
                    this.RaisePropertyChanged("RouteFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RouteID {
            get {
                return this.RouteIDField;
            }
            set {
                if ((this.RouteIDField.Equals(value) != true)) {
                    this.RouteIDField = value;
                    this.RaisePropertyChanged("RouteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteTo {
            get {
                return this.RouteToField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteToField, value) != true)) {
                    this.RouteToField = value;
                    this.RaisePropertyChanged("RouteTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insert_ScheduleInfo", Namespace="http://schemas.datacontract.org/2004/07/Bus_Service.Classes")]
    [System.SerializableAttribute()]
    public partial class Insert_ScheduleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RouteCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RouteidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScheduleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Busid {
            get {
                return this.BusidField;
            }
            set {
                if ((this.BusidField.Equals(value) != true)) {
                    this.BusidField = value;
                    this.RaisePropertyChanged("Busid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((this.DepartureTimeField.Equals(value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RouteCost {
            get {
                return this.RouteCostField;
            }
            set {
                if ((this.RouteCostField.Equals(value) != true)) {
                    this.RouteCostField = value;
                    this.RaisePropertyChanged("RouteCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Routeid {
            get {
                return this.RouteidField;
            }
            set {
                if ((this.RouteidField.Equals(value) != true)) {
                    this.RouteidField = value;
                    this.RaisePropertyChanged("Routeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScheduleID {
            get {
                return this.ScheduleIDField;
            }
            set {
                if ((this.ScheduleIDField.Equals(value) != true)) {
                    this.ScheduleIDField = value;
                    this.RaisePropertyChanged("ScheduleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insert_availseats", Namespace="http://schemas.datacontract.org/2004/07/Bus_Service.Classes")]
    [System.SerializableAttribute()]
    public partial class Insert_availseats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DoJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GeneralSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScheduleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AID {
            get {
                return this.AIDField;
            }
            set {
                if ((this.AIDField.Equals(value) != true)) {
                    this.AIDField = value;
                    this.RaisePropertyChanged("AID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableSeats {
            get {
                return this.AvailableSeatsField;
            }
            set {
                if ((this.AvailableSeatsField.Equals(value) != true)) {
                    this.AvailableSeatsField = value;
                    this.RaisePropertyChanged("AvailableSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DoJ {
            get {
                return this.DoJField;
            }
            set {
                if ((this.DoJField.Equals(value) != true)) {
                    this.DoJField = value;
                    this.RaisePropertyChanged("DoJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GeneralSeats {
            get {
                return this.GeneralSeatsField;
            }
            set {
                if ((this.GeneralSeatsField.Equals(value) != true)) {
                    this.GeneralSeatsField = value;
                    this.RaisePropertyChanged("GeneralSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScheduleID {
            get {
                return this.ScheduleIDField;
            }
            set {
                if ((this.ScheduleIDField.Equals(value) != true)) {
                    this.ScheduleIDField = value;
                    this.RaisePropertyChanged("ScheduleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CS", Namespace="http://schemas.datacontract.org/2004/07/Bus_Service.Classes")]
    [System.SerializableAttribute()]
    public partial class CS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRegistration", Namespace="http://schemas.datacontract.org/2004/07/Bus_Service.Classes")]
    [System.SerializableAttribute()]
    public partial class CustomerRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Confirm_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Confirm_Password {
            get {
                return this.Confirm_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.Confirm_PasswordField, value) != true)) {
                    this.Confirm_PasswordField = value;
                    this.RaisePropertyChanged("Confirm_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_type {
            get {
                return this.Customer_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_typeField, value) != true)) {
                    this.Customer_typeField = value;
                    this.RaisePropertyChanged("Customer_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dob {
            get {
                return this.DobField;
            }
            set {
                if ((this.DobField.Equals(value) != true)) {
                    this.DobField = value;
                    this.RaisePropertyChanged("Dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((this.MobileNoField.Equals(value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pincode {
            get {
                return this.PincodeField;
            }
            set {
                if ((this.PincodeField.Equals(value) != true)) {
                    this.PincodeField = value;
                    this.RaisePropertyChanged("Pincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertBusInfo", ReplyAction="http://tempuri.org/IService1/InsertBusInfoResponse")]
        string InsertBusInfo(Bus_Client.ServiceReference1.Insert_BusInfo B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertBusInfo", ReplyAction="http://tempuri.org/IService1/InsertBusInfoResponse")]
        System.Threading.Tasks.Task<string> InsertBusInfoAsync(Bus_Client.ServiceReference1.Insert_BusInfo B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRouteInfo", ReplyAction="http://tempuri.org/IService1/InsertRouteInfoResponse")]
        string InsertRouteInfo(Bus_Client.ServiceReference1.Insert_RouteInfo R);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRouteInfo", ReplyAction="http://tempuri.org/IService1/InsertRouteInfoResponse")]
        System.Threading.Tasks.Task<string> InsertRouteInfoAsync(Bus_Client.ServiceReference1.Insert_RouteInfo R);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusid", ReplyAction="http://tempuri.org/IService1/GetBusidResponse")]
        Bus_Client.ServiceReference1.Insert_BusInfo[] GetBusid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusid", ReplyAction="http://tempuri.org/IService1/GetBusidResponse")]
        System.Threading.Tasks.Task<Bus_Client.ServiceReference1.Insert_BusInfo[]> GetBusidAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRouteid", ReplyAction="http://tempuri.org/IService1/GetRouteidResponse")]
        Bus_Client.ServiceReference1.Insert_RouteInfo[] GetRouteid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRouteid", ReplyAction="http://tempuri.org/IService1/GetRouteidResponse")]
        System.Threading.Tasks.Task<Bus_Client.ServiceReference1.Insert_RouteInfo[]> GetRouteidAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertScheduleInfo", ReplyAction="http://tempuri.org/IService1/InsertScheduleInfoResponse")]
        string InsertScheduleInfo(Bus_Client.ServiceReference1.Insert_ScheduleInfo S);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertScheduleInfo", ReplyAction="http://tempuri.org/IService1/InsertScheduleInfoResponse")]
        System.Threading.Tasks.Task<string> InsertScheduleInfoAsync(Bus_Client.ServiceReference1.Insert_ScheduleInfo S);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetScheduleId", ReplyAction="http://tempuri.org/IService1/GetScheduleIdResponse")]
        Bus_Client.ServiceReference1.Insert_ScheduleInfo[] GetScheduleId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetScheduleId", ReplyAction="http://tempuri.org/IService1/GetScheduleIdResponse")]
        System.Threading.Tasks.Task<Bus_Client.ServiceReference1.Insert_ScheduleInfo[]> GetScheduleIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSecId", ReplyAction="http://tempuri.org/IService1/getSecIdResponse")]
        int[] getSecId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSecId", ReplyAction="http://tempuri.org/IService1/getSecIdResponse")]
        System.Threading.Tasks.Task<int[]> getSecIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSeatsAvailInfo", ReplyAction="http://tempuri.org/IService1/InsertSeatsAvailInfoResponse")]
        string InsertSeatsAvailInfo(Bus_Client.ServiceReference1.Insert_availseats A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSeatsAvailInfo", ReplyAction="http://tempuri.org/IService1/InsertSeatsAvailInfoResponse")]
        System.Threading.Tasks.Task<string> InsertSeatsAvailInfoAsync(Bus_Client.ServiceReference1.Insert_availseats A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCS", ReplyAction="http://tempuri.org/IService1/InsertCSResponse")]
        string InsertCS(Bus_Client.ServiceReference1.CS Co);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCS", ReplyAction="http://tempuri.org/IService1/InsertCSResponse")]
        System.Threading.Tasks.Task<string> InsertCSAsync(Bus_Client.ServiceReference1.CS Co);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountry", ReplyAction="http://tempuri.org/IService1/GetCountryResponse")]
        string[] GetCountry();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountry", ReplyAction="http://tempuri.org/IService1/GetCountryResponse")]
        System.Threading.Tasks.Task<string[]> GetCountryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetState", ReplyAction="http://tempuri.org/IService1/GetStateResponse")]
        string[] GetState(string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetState", ReplyAction="http://tempuri.org/IService1/GetStateResponse")]
        System.Threading.Tasks.Task<string[]> GetStateAsync(string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getmobileno", ReplyAction="http://tempuri.org/IService1/GetmobilenoResponse")]
        Bus_Client.ServiceReference1.CustomerRegistration[] Getmobileno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getmobileno", ReplyAction="http://tempuri.org/IService1/GetmobilenoResponse")]
        System.Threading.Tasks.Task<Bus_Client.ServiceReference1.CustomerRegistration[]> GetmobilenoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer", ReplyAction="http://tempuri.org/IService1/InsertCustomerResponse")]
        string InsertCustomer(Bus_Client.ServiceReference1.CustomerRegistration Cr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer", ReplyAction="http://tempuri.org/IService1/InsertCustomerResponse")]
        System.Threading.Tasks.Task<string> InsertCustomerAsync(Bus_Client.ServiceReference1.CustomerRegistration Cr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Userlogin", ReplyAction="http://tempuri.org/IService1/UserloginResponse")]
        Bus_Client.ServiceReference1.CustomerRegistration Userlogin(long Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Userlogin", ReplyAction="http://tempuri.org/IService1/UserloginResponse")]
        System.Threading.Tasks.Task<Bus_Client.ServiceReference1.CustomerRegistration> UserloginAsync(long Username, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Bus_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Bus_Client.ServiceReference1.IService1>, Bus_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertBusInfo(Bus_Client.ServiceReference1.Insert_BusInfo B) {
            return base.Channel.InsertBusInfo(B);
        }
        
        public System.Threading.Tasks.Task<string> InsertBusInfoAsync(Bus_Client.ServiceReference1.Insert_BusInfo B) {
            return base.Channel.InsertBusInfoAsync(B);
        }
        
        public string InsertRouteInfo(Bus_Client.ServiceReference1.Insert_RouteInfo R) {
            return base.Channel.InsertRouteInfo(R);
        }
        
        public System.Threading.Tasks.Task<string> InsertRouteInfoAsync(Bus_Client.ServiceReference1.Insert_RouteInfo R) {
            return base.Channel.InsertRouteInfoAsync(R);
        }
        
        public Bus_Client.ServiceReference1.Insert_BusInfo[] GetBusid() {
            return base.Channel.GetBusid();
        }
        
        public System.Threading.Tasks.Task<Bus_Client.ServiceReference1.Insert_BusInfo[]> GetBusidAsync() {
            return base.Channel.GetBusidAsync();
        }
        
        public Bus_Client.ServiceReference1.Insert_RouteInfo[] GetRouteid() {
            return base.Channel.GetRouteid();
        }
        
        public System.Threading.Tasks.Task<Bus_Client.ServiceReference1.Insert_RouteInfo[]> GetRouteidAsync() {
            return base.Channel.GetRouteidAsync();
        }
        
        public string InsertScheduleInfo(Bus_Client.ServiceReference1.Insert_ScheduleInfo S) {
            return base.Channel.InsertScheduleInfo(S);
        }
        
        public System.Threading.Tasks.Task<string> InsertScheduleInfoAsync(Bus_Client.ServiceReference1.Insert_ScheduleInfo S) {
            return base.Channel.InsertScheduleInfoAsync(S);
        }
        
        public Bus_Client.ServiceReference1.Insert_ScheduleInfo[] GetScheduleId() {
            return base.Channel.GetScheduleId();
        }
        
        public System.Threading.Tasks.Task<Bus_Client.ServiceReference1.Insert_ScheduleInfo[]> GetScheduleIdAsync() {
            return base.Channel.GetScheduleIdAsync();
        }
        
        public int[] getSecId() {
            return base.Channel.getSecId();
        }
        
        public System.Threading.Tasks.Task<int[]> getSecIdAsync() {
            return base.Channel.getSecIdAsync();
        }
        
        public string InsertSeatsAvailInfo(Bus_Client.ServiceReference1.Insert_availseats A) {
            return base.Channel.InsertSeatsAvailInfo(A);
        }
        
        public System.Threading.Tasks.Task<string> InsertSeatsAvailInfoAsync(Bus_Client.ServiceReference1.Insert_availseats A) {
            return base.Channel.InsertSeatsAvailInfoAsync(A);
        }
        
        public string InsertCS(Bus_Client.ServiceReference1.CS Co) {
            return base.Channel.InsertCS(Co);
        }
        
        public System.Threading.Tasks.Task<string> InsertCSAsync(Bus_Client.ServiceReference1.CS Co) {
            return base.Channel.InsertCSAsync(Co);
        }
        
        public string[] GetCountry() {
            return base.Channel.GetCountry();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCountryAsync() {
            return base.Channel.GetCountryAsync();
        }
        
        public string[] GetState(string Country) {
            return base.Channel.GetState(Country);
        }
        
        public System.Threading.Tasks.Task<string[]> GetStateAsync(string Country) {
            return base.Channel.GetStateAsync(Country);
        }
        
        public Bus_Client.ServiceReference1.CustomerRegistration[] Getmobileno() {
            return base.Channel.Getmobileno();
        }
        
        public System.Threading.Tasks.Task<Bus_Client.ServiceReference1.CustomerRegistration[]> GetmobilenoAsync() {
            return base.Channel.GetmobilenoAsync();
        }
        
        public string InsertCustomer(Bus_Client.ServiceReference1.CustomerRegistration Cr) {
            return base.Channel.InsertCustomer(Cr);
        }
        
        public System.Threading.Tasks.Task<string> InsertCustomerAsync(Bus_Client.ServiceReference1.CustomerRegistration Cr) {
            return base.Channel.InsertCustomerAsync(Cr);
        }
        
        public Bus_Client.ServiceReference1.CustomerRegistration Userlogin(long Username, string Password) {
            return base.Channel.Userlogin(Username, Password);
        }
        
        public System.Threading.Tasks.Task<Bus_Client.ServiceReference1.CustomerRegistration> UserloginAsync(long Username, string Password) {
            return base.Channel.UserloginAsync(Username, Password);
        }
    }
}
